# Generated by Django 4.0.3 on 2024-02-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='VIN',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
