# Generated by Django 4.0.3 on 2024-02-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='VIN',
            new_name='vin',
        ),
    ]
