# Generated by Django 4.0.3 on 2024-02-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_rename_vin_automobilevo_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
